### PR TITLE
Fix Gradle 2.6 compatibility

### PR DESCRIPTION
**Pull request by ngyukman**
Compile with gradle 2.6 could fix the following issue:

```Caused by: org.gradle.api.GradleException: Could not generate a proxy class for class com.ullink.IkvmDoc.
        at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:201)
        at org.gradle.api.internal.AbstractClassGenerator.generate(AbstractClassGenerator.java:64)
        at org.gradle.api.internal.project.taskfactory.TaskFactory.create(TaskFactory.java:115)
        at org.gradle.api.internal.project.taskfactory.TaskFactory.createTask(TaskFactory.java:77)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.createTask(AnnotationProcessingTaskFactory.java:99)
        at org.gradle.api.internal.project.taskfactory.DependencyAutoWireTaskFactory.createTask(DependencyAutoWireTaskFactory.java:39)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:62)
        at org.gradle.api.internal.project.AbstractProject.task(AbstractProject.java:878)
        at org.gradle.api.Project$task$0.call(Unknown Source)
        at com.ullink.IkvmPlugin.apply(IkvmPlugin.groovy:28)
        at com.ullink.IkvmPlugin.apply(IkvmPlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
        at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
        ... 61 more
Caused by: java.lang.NoClassDefFoundError: org/gradle/platform/base/internal/toolchain/ToolResolver
        at org.gradle.internal.reflect.ClassInspector.inspectClass(ClassInspector.java:67)
        at org.gradle.internal.reflect.ClassInspector.visitGraph(ClassInspector.java:51)
        at org.gradle.internal.reflect.ClassInspector.inspect(ClassInspector.java:31)
        at org.gradle.api.internal.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:260)
        at org.gradle.api.internal.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:216)
        at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:95)
        ... 74 more
Caused by: java.lang.ClassNotFoundException: org.gradle.platform.base.internal.toolchain.ToolResolver```

### CODE REVIEW

**Comment by gluck** [comment]
Does the plugin still work w/ gradle < 2.6 when compiled w/ gradle 2.6 ?

**Comment by ngyukman** [comment]
it works on 2.2 & 2.5 too
but indeed I missed that I have to modify the dependencies to make the plugin work for me

**Comment by gluck** [comment]
Thx !
